/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class miku_lib_common_Native_NativeUtil */

#ifndef _Included_miku_lib_common_Native_NativeUtil
#define _Included_miku_lib_common_Native_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     miku_lib_common_Native_NativeUtil
 * Method:    Kill
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_miku_lib_common_Native_NativeUtil_Kill
  (JNIEnv *, jclass, jobject);

/*
 * Class:     miku_lib_common_Native_NativeUtil
 * Method:    TEST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_miku_lib_common_Native_NativeUtil_TEST
  (JNIEnv *, jclass);

/*
 * Class:     miku_lib_common_Native_NativeUtil
 * Method:    GetClass
 * Signature: (Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_miku_lib_common_Native_NativeUtil_GetClass
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
